prooph_service_bus:
    command_buses:
        app_command_bus: ~
    event_buses:
        app_event_bus: ~

services:
    _defaults:
        autowire: true

    Prooph\Bundle\ServiceBus\CommandBus: '@prooph_service_bus.app_command_bus'
    Prooph\ServiceBus\EventBus: '@prooph_service_bus.app_event_bus'

    # Make sure App\Messaging\* services are not overriden in `config/services.yaml`
    command_handlers:
        resource: '../../src/Messaging/Command/*Handler.php'
        namespace: App\Messaging\Command\
        public: true
        tags:
            - { name: 'prooph_service_bus.app_command_bus.route_target', message_detection: true }

    event_listeners:
        resource: '../../src/Messaging/Event/*Listener.php'
        namespace: App\Messaging\Event\
        public: true
        tags:
            - { name: 'prooph_service_bus.app_event_bus.route_target', message_detection: true }
